name: flutter_test_0630
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^1.1.0
  apple_sign_in: ^0.1.0
  app_tracking_transparency: ^1.1.0+1
  auto_size_text: ^2.1.0
  bot_toast: ^3.0.4
  cached_network_image: ^2.0.0
  carousel_slider: ^2.2.1
  channel_talk_flutter: ^1.1.0
  chewie: ^0.12.2
  cupertino_icons: ^1.0.3
  cupertino_will_pop_scope: ^1.0.4
  custom_refresh_indicator: ^0.9.0
  device_info: ^0.4.2+7
  dio: ^3.0.10
  double_back_to_close_app: ^1.2.0
  email_validator: ^1.0.6
  equatable: ^1.2.3
  exif: ^1.0.3
  extended_image: ^1.3.0
  firebase_analytics: ^5.0.16
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_messaging: ^6.0.16
  firebase_dynamic_links: ^0.5.0+11

  flutter_animated_dialog: ^1.2.0
  flutter_app_badger: ^1.1.2
  flutter_bloc: ^6.0.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_launcher_icons: ^0.7.5
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^1.4.1
  flutter_masked_text: ^0.8.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_screenutil: ^2.3.1
  flutter_secure_storage: ^3.2.1+1
  flutter_signature_pad: ^2.0.2
  flutter_sound_lite: ^6.3.1+1
  flutter_swiper : ^1.1.2
  flutter_svg: ^0.19.0
  fluttertoast: ^7.1.8
  flutter_webview_plugin:  ^0.3.10+1
  flutter_widgets: ^0.1.11
  flutter_widget_from_html_core: ^0.4.3
  google_sign_in: ^4.5.3
  http: ^0.12.0
  iamport_flutter: ^0.9.13
  image_picker: ^0.6.7+7
  intercom_flutter: ^2.3.2
  intl: ^0.16.0
  launch_review: ^2.0.0
  lottie: ^0.6.0
  meta: ^1.1.6
  package_info: ^0.4.3
  page_transition: ^1.1.6
  path: ^1.6.4
  path_provider: ^1.6.9
  pdf: ^1.9.0
  percent_indicator: ^2.1.1
  permission_handler: ^5.0.0
  printing: ^3.5.0
  rxdart: ^0.24.1
  screenshot: ^0.2.0
  shared_preferences: ^0.5.3+4
  smooth_page_indicator: ^0.2.0
  snaplist: ^0.1.8
  url_launcher: ^5.7.10
  version: ^1.0.0
  video_player: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  mockito: ^4.1.1


flutter:
  uses-material-design: true