name: flutter_test_0630
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.0
  apple_sign_in:
    path: ../flutter_apple_sign_in
#  apple_sign_in: ^0.1.0
  app_tracking_transparency: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  channel_talk_flutter:
    path: ../channel_talk_flutter
#  channel_talk_flutter: ^1.1.0
  chewie: ^1.2.2
  cupertino_icons: ^1.0.3
  cupertino_will_pop_scope: ^1.1.0
  custom_refresh_indicator: ^1.0.0
  device_info: ^2.0.2
  dio: ^4.0.0
  double_back_to_close_app: ^2.0.1
  email_validator: ^2.0.1
  equatable: ^2.0.3
  exif: ^3.0.0
  extended_image: ^4.1.0
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  firebase_messaging: ^10.0.3
  firebase_dynamic_links: ^2.0.6

  flutter_animated_dialog: ^2.0.0
  flutter_app_badger: ^1.2.0
  flutter_bloc: ^7.0.1
#  flutter_cupertino_localizations: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^6.0.0
#  flutter_masked_text: ^0.8.0
#  flutter_full_pdf_viewer: ^1.0.6
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^4.2.0
  flutter_signature_pad: ^3.0.0
  flutter_sound_lite: ^8.1.4
#  flutter_swiper : ^1.1.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  flutter_webview_plugin: ^0.4.0
#  flutter_widgets: ^0.1.11
  flutter_widget_from_html_core: ^0.6.1+3
  google_sign_in: ^5.0.4
  http: ^0.13.3
  iamport_flutter: ^0.10.0-dev.1
  image_picker: ^0.8.1+3
  intercom_flutter: ^3.2.1
  intl: ^0.17.0
  launch_review: ^3.0.1
  lottie: ^1.0.1
  meta: ^1.3.0
  package_info: ^2.0.2
  page_transition: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  pdf: ^3.4.2
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.2
  printing: ^5.4.3
  rxdart: ^0.27.1
  screenshot: ^1.2.1
  shared_preferences: ^2.0.6
  smooth_page_indicator: ^0.3.0-nullsafety.0
#  snaplist: ^0.1.8
  url_launcher: ^6.0.8
  version: ^2.0.0
  video_player: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  mockito: ^5.0.10


flutter:
  uses-material-design: true